feat: реализовать локальное хранение сущностей User и Item
ciiska5/java-shareit pull request #1
Opened 2023-06-12 13:46 UTC by ciiska5

ShareIt - реализовано локальное хранение пользователей и их вещей для аренды.

2023-06-13 15:06 UTC, alexache requested changes

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  /**
Такие комментарии можно подчистить или наполнить смыслом

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDaoImpl.java
> +    private final UserDAO userDAO;
Сторадж вещей не должен ничего знать о других стораджах: его задача только хранить объекты. Взаимодействие с ДАО юзеров должно быть на сервисе

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDaoImpl.java
> +                .filter(item1 -> item1.getId().equals(itemId))
Немного затратный поиск полным перебором. Лучше заложить 2 словаря: один про маппинг юзеров на их вещи (как сейчас), а второй айди вещи на объект вещи, так будет оптимальнее

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDaoImpl.java
> +        if (itemDto.isEmpty()) {
С Optional есть более изящная конструкция с return itemDto.orElseThrow(() -> new ItemNotFoundException(...));

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDaoImpl.java
> +        return ItemMapper.toItemDto(item);
Маппинг на сторадже тоже выглядит излишним. Есть принцип single responsibility: у тебя на сторадже сейчас слишком много функций, маппером может заниматься сервис или контроллер

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDaoImpl.java
> +            foundItemsDto = getAllItemsDto()
Зачем сначала маппить в ДТО: а потом искать? Выглядит лишней работой

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long userId; // владелец вещи
Тут будет логично хранить объект юзера: а не просто айди

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserDAOImpl.java
> +        if (users.stream()
Хорошая задумка с проверкой: но не очень оптимальная реализация, лучше завести отдельный сет для хранения текущих имейлов пользователей: тогда проверка будет простой и быстрой

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserDAOImpl.java
> +        if (users.stream()
Тоже немного не оптимальная проверка: может юзеров лучше хранить в мапе айди на объект?

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserDAOImpl.java
> +        checkUsersExistenceById(userId);
Зачем эта проверка: если можно просто результат получения по айди проверять?

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private String name; // имя или логин пользователя;
А может стоит добавить валидации?

2023-06-13 15:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User addNewUser(@Valid @RequestBody User user) {
Что-то запуталось здесь: User должен быть моделью данных в сторадже, а UserDto объектом для взаимодействия контроллера

2023-06-18 07:21 UTC, ciiska5 commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDaoImpl.java
> +        return ItemMapper.toItemDto(item);
Маппингом занимаются методы объекта ItemMapper, а не сторадж, сторадж только использует эту функцию. Разве не так?

2023-06-18 09:13 UTC, ciiska5 commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDaoImpl.java
> +        return ItemMapper.toItemDto(item);
Понял, в чем суть:)

2023-06-18 10:24 UTC, ciiska5 commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserDAOImpl.java
> +        checkUsersExistenceById(userId);
Сделал так, чтобы не возвращал null, а сразу выбрасывал ошибку

2023-06-19 17:14 UTC, alexache approved these changes

2023-06-19 17:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        User user = userDAO.getUserById(userId);
Это и checkUsersExistenceById делают одну работу, можно обойтись одним вызовом получения пользователя по айди

2023-06-19 17:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserDAOImpl.java
> +        checkUsersExistenceById(userId);
User user = users.get(userId);
if (user == null) {
   throws new UserNotFoundException(..);
} 
return user;
решает ту же задачу одним вызовом к стораджу

2023-06-19 17:14 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserDAOImpl.java
> +        return users.values().parallelStream().collect(Collectors.toList());
return new ArrayList<>(users.values()); выглядит проще,  Не уверен, что параллельные стримы и коллектор будут быстрее

2023-06-30 19:36 UTC, merged