Add bookings
ciiska5/java-shareit pull request #3
Opened 2023-06-30 19:57 UTC by ciiska5

2023-07-01 09:12 UTC, alexache requested changes

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;// вещь, которую пользователь бронирует
Очень не стоит совмещать ДТО и модели в одном классе. ДТО с ДТО, модели с моделям. К тому же, для ДТО внутри других ДТО лучше заводить свои отдельные классы ДТО, чтобы использовать только нужные поля

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Эта аннотация не подходит для JPA моделей, equals/hashcode не подходят

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServImpl.java
> +    private final Sort sort = Sort.by(Sort.Direction.DESC, "start"); //параметр для сортировки бронирований от старых к новым
можно и статик тогда, для обозначения того, что это константа

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServImpl.java
> +        bookingRepository.save(booking);
Нужно использовать возвращаемый объект от этого метода, в котором будет выставлен айди

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServImpl.java
> +        Long bookingBookerId = booking.getBooker().getId();
А если вещь не бронировали?

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private ItemRequest request; //если вещь была создана по запросу другого пользователя, то в этом
Модель в ДТО классе

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userItems == null) {
Немного странная проверка, а где проверка что он владелец вещи?

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<Booking> ascBookingList = bookingRepository.findAllByItemIdOrderByStartAsc(itemId);
Нельзя делать запросы к базе внутри цикла

2023-07-01 09:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
Какой-то неоптимальный способ, почему не найти вещи по тексту одним запросом к базе?

2023-07-01 18:06 UTC, ciiska5 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServImpl.java
> +        Long bookingBookerId = booking.getBooker().getId();
В этом случае не будет объекта букинга и выбросится исключение в строке 93.

2023-07-03 07:22 UTC, alexache approved these changes

2023-07-14 02:33 UTC, merged