feat: добавить запрос вещи
ciiska5/java-shareit pull request #4
Opened 2023-09-01 02:03 UTC by ciiska5

2023-09-02 20:10 UTC, alexache requested changes

2023-09-02 20:10 UTC, alexache commented on pom.xml
> +												<minimum>0.69</minimum>
Эти параметры по покрытию нельзя менять

2023-09-02 20:10 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                 @RequestParam(defaultValue = "0") int from,
У параметров не хватает валидации

2023-09-02 20:10 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/service/BookingServImpl.java
> +            throw new PaginationParamException("Некорректно заданы параметры пагинации");
Это лучше сделать аннотациями

2023-09-02 20:10 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> -    private UserDto requestor; // пользователь, создавший запрос
Поля сущности описаны в ТЗ, это не они

2023-09-02 20:10 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        itemRequestDtoList.forEach(this::addItemListToItemRequestDto);
Здесь в цикле вызывется метод, в котором есть запрос к базе - получается запрос к базе в цикле, что неприемлимо

2023-09-02 20:10 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTests/BookingControllerTest.java
> +    ObjectMapper objectMapper;
У полей, даже в тестах, не помешают модификаторы доступа

2023-09-02 20:10 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTests/BookingControllerTest.java
> +                .andExpect(jsonPath("$.status", is(testBookingDto.getStatus().toString()), String.class));
Хорошо бы еще добавить валидации, что метод сервиса был вызван и единожды

2023-09-02 20:10 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTests/BookingDtoTest.java
> +        assertThat(result).hasJsonPathStringValue("$.start");
Стоит проверять и само значение

2023-09-02 20:10 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTests/BookingServiceImplIntegrationTest.java
> +@Transactional
Немного странная аннотация на тестовом классе

2023-09-02 20:10 UTC, alexache commented on src/test/java/ru/practicum/shareit/bookingTests/BookingServiceTest.java
> +public class BookingServiceTest {
BookingServiceImplTest

2023-09-03 07:16 UTC, ciiska5 commented on src/test/java/ru/practicum/shareit/bookingTests/BookingServiceImplIntegrationTest.java
> +@Transactional
Использую, чтобы данные в БД откаnывались для сохранения его первоначального состояния. В практикуме в примерах также это практиковалось: https://practicum.yandex.ru/learn/java-developer/courses/ec5e03ed-e12f-43c5-93d1-638a79454e03/sprints/99912/topics/5358fb86-2387-40c3-825e-f52551fa4815/lessons/20d0b50b-ef2f-480e-9d04-dbf47fe06287/

2023-09-03 11:32 UTC, ciiska5 commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> -    private UserDto requestor; // пользователь, создавший запрос
Не совсем понял, какие поля я указал неверно. В ТЗ написано, что "Для каждого запроса должны указываться **описание**, **дата и время создания** и **список ответов в формате**...". Как я понял, список ответов в формате - это список объектов ItemDto

2023-09-04 05:10 UTC, alexache requested changes

2023-09-04 05:10 UTC, alexache commented on pom.xml
> +												<minimum>0.9</minimum>
Остальные 2 параметра по покрытию тоже нужно вернуть к значениям по умолчанию, можно увидеть по полному диффу какие это еще параметры

2023-09-04 20:30 UTC, alexache approved these changes

2023-09-05 00:05 UTC, merged